#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
go build -tags static -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/rancher-auth-service
