#!/bin/bash
set -e -x

cd $(dirname $0)/..

echo Running tests

PACKAGES=". $(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

[ "${ARCH}" == "amd64" ] && RACE=-race
CC="gcc -lm" go test -ldflags ${RACE} -cover -tags=test ${PACKAGES}
